---
# MySQL Deployment with Resource Requests
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  annotations:
    harness.io/direct-apply: "true"
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Test@123"
        - name: MYSQL_DATABASE
          value: "bankappdb"
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    harness.io/direct-apply: "true"
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
# BankApp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
      harness.io/color: blue
  template:
    metadata:
      labels:
        app: bankapp
        harness.io/color: blue
    spec:
      containers:
      - name: bankapp
        image: arvindpdige/bankapp:{{ .Values.TAG }} # Adjust the image tag for the blue version
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Test@123
        resources:
          requests:
            memory: "500Mi"
            cpu: "300m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
---
# BankApp service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service-1
  annotations:
    harness.io/primary-service: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp
    harness.io/color: blue
---
# BankApp service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service-2
  annotations:
    harness.io/stage-service: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp
    harness.io/color: blue
