apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
      harness.io/color: blue
  template:
    metadata:
      labels:
        app: bankapp
        harness.io/color: blue
    spec:
      containers:
      - name: bankapp
        image: arvindpdige/bankapp:<+pipeline.variables.tag> 
