pipeline:
  name: gcp-mvn-reg-GAR
  identifier: gcpmvnregGAR
  projectIdentifier: GCPTest
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitall
        repoName: Blue-Green
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.minikubeconn
              namespace: maven
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Build_And_Push_WAR
                  identifier: Build_And_Push_WAR
                  spec:
                    connectorRef: account.Dockerhub
                    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
                    shell: Sh
                    command: |-
                      echo "Authenticating with Google Cloud..."
                      python3 - <<'EOF'
                      import os, json
                      key = os.environ.get("GCP_KEY_JSON")
                      if not key:
                        raise SystemExit("Missing GCP_KEY_JSON")
                      key_json = json.loads(key)
                      with open("/harness/gcp-key.json", "w") as f:
                        json.dump(key_json, f)
                      EOF

                      gcloud auth activate-service-account --key-file=/harness/gcp-key.json
                      gcloud config set project harness-475313

                      gcloud auth list

                      # gcloud artifacts repositories list --location=asia-south1
                      # cat /harness/gcp-key.json
                      # export GOOGLE_APPLICATION_CREDENTIALS=/harness/gcp-key.json
                    envVariables:
                      GCP_KEY_JSON: <+secrets.getValue("gcp-sa")>
              - step:
                  type: Run
                  name: Push_To_Gar
                  identifier: Build_jar
                  spec:
                    connectorRef: account.Dockerhub
                    image: maven:3-openjdk-17
                    shell: Bash
                    command: |-
                      echo "Using service account key from /harness/gcp-key.json"
                      export GOOGLE_APPLICATION_CREDENTIALS=/harness/gcp-key.json

                      ENCODED_KEY=$(base64 -w0 /harness/gcp-key.json)

                      mvn clean deploy \
                        -DskipTests \
                        -DaltDeploymentRepository=artifact-registry::default::https://_json_key_base64:${ENCODED_KEY}@asia-south1-maven.pkg.dev/harness-475313/gcp-mvn-snap-reg
                        # -DpomFile=pom.xml -Dfile=target/*.jar
                        # -Dgcp.service.account.file=/tmp/gcp-key.json \
                        # -Dgcp.project.id=harness-475313

                      echo "✅ JAR uploaded successfully!......"
